apiVersion: apps/v1
kind: Deployment
metadata:
  name: MenuItemListing-deployment
  labels:
    app: MenuItemListing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MenuItemListing  
  template:
    metadata:
      labels:
        app: MenuItemListing
    spec:
      containers:
      - name: MenuItemListing
        image: menuitemlisting.azurecr.io/menuitemlistrepo:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: menuitemlistingcredentails
---
apiVersion: v1
kind: Service
metadata:
  name: menuitemlistingsvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: MenuItemListing